apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: su-se-bakover
  namespace: supstonad
  labels:
    team: supstonad
spec:
  groups:
    - name: su-se-bakover
      rules:
        #https://doc.nais.io/observability/logging/reference/loki-metrics/
        - alert: su-se-bakover-error-logg-grafana
          expr: 'sum_over_time(loki:service:loglevel:count1m{service_name="su-se-bakover", detected_level="error"}[15m]) > 0'
          for: 1s
          annotations:
            consequence: "su-se-bakover har fått en ny error i loggen siste 15 min"
            action: "Det er logget en melding med log level ERROR. Sjekk logger her: `{{LOGS_URL_LOKI}}` `{{LOGS_URL}}`"
          labels:
            namespace: supstonad
            severity: critical
        - alert: su-se-bakover-pods-available
          expr: sum(kube_deployment_status_replicas_available{deployment="su-se-bakover"}) < 1
          for: 1m
          annotations:
            consequence: "Tilgjengelige kubernetes pods for su-se-bakover er mindre enn 1"
            action: "`kubectl describe pod {{ $labels.kubernetes_pod_name }}` for events, og `kubectl logs {{ $labels.kubernetes_pod_name }}` for logger"
          labels:
            namespace: supstonad
            severity: critical
        - alert: su-se-bakover-metrics-scrape-feilet
          expr: sum(up{app="su-se-bakover", job="kubernetes-pods"}) < 1
          for: 1m
          annotations:
            consequence: "su-se-bakover sitt /metrics endepunktet har vært utilgjengelig i minst 1 minutt"
            action: "`kubectl describe pod {{ $labels.kubernetes_pod_name }}` for events, og `kubectl logs {{ $labels.kubernetes_pod_name }}` for logger"
          labels:
            namespace: supstonad
            severity: critical
        - alert: su-se-bakover-direct-buffer-hoy
          # 75% av -XX:MaxDirectMemorySize=512m
          expr: max(su_jvm_direct_buffer_used_bytes{app="su-se-bakover"}) > 402653184
          for: 5m
          annotations:
            consequence: "su-se-bakover bruker høy andel direct-buffer minne i mer enn 5 minutter"
            action: "Sjekk metrikker for `su_jvm_direct_buffer_used_bytes` og logger for backend-feil i `{{LOGS_URL_LOKI}}`"
          labels:
            namespace: supstonad
            severity: warning
        - alert: su-se-bakover-direct-buffer-kritisk
          # 87.5% av -XX:MaxDirectMemorySize=512m
          expr: max(su_jvm_direct_buffer_used_bytes{app="su-se-bakover"}) > 469762048
          for: 2m
          annotations:
            consequence: "su-se-bakover er nær direct-buffer OOM"
            action: "Undersøk pågående store responses/base64 payloads og vurder nedskalering av samtidighet eller høyere direct-memory"
          labels:
            namespace: supstonad
            severity: critical
