apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: su-se-bakover
  namespace: supstonad
  labels:
    team: supstonad
spec:
  azure:
    application:
      enabled: true
      tenant: {{ tenant }}
      claims:
        extra:
          - "NAVident"
        groups:
          - id: {{ env.AZURE_GROUP_ATTESTANT }}
          - id: {{ env.AZURE_GROUP_SAKSBEHANDLER }}
          - id: {{ env.AZURE_GROUP_VEILEDER }}
          - id: {{ env.AZURE_GROUP_DRIFT }}
  accessPolicy:
    inbound:
      rules:
        - application: su-se-framover
        - application: "frikorttjenester"
          namespace: "teamfrikort"
          permissions:
            roles:
              - frikort
    outbound:
      rules:
        - application: {{ kodeverk-application }}
          namespace: team-rocket
  image: {{ image }}
  liveness:
    path: /isalive
    initialDelay: 25
    timeout: 10
  readiness:
    path: /isready
    initialDelay: 25
    timeout: 10
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      memory: 4Gi
    requests:
      memory: 1Gi
      cpu: 1000m
  ingresses:
    - {{ ingress1 }}
    - {{ ingress2 }}
  webproxy: true
  prometheus:
    enabled: true
    path: /metrics
  secureLogs:
    enabled: true
  leaderElection: true
  kafka:
    pool: {{ kafka-pool }}
  vault:
    enabled: true
    paths:
      - mountPath: /var/run/secrets/nais.io/srvuser
        kvPath: /serviceuser/data/{{ secret_env }}/srvsupstonad
  env:
     {{#each env}}
      - name: {{@key}}
        value: "{{this}}"
     {{/each}}
