pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
}
plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.5.0"
}
rootProject.name = "su-se-bakover"

include("application")
include("behandling:domain")
include("behandling:klage:domain")
include("behandling:regulering:domain")
include("behandling:revurdering:domain")
include("behandling:søknadsbehandling:domain")
include("beregning")
include("client")
include("common:domain")
include("common:infrastructure")
include("common:infrastructure:cxf")
include("common:presentation")
include("database")
include("datapakker:soknad")
include("dokument:application")
include("dokument:domain")
include("dokument:infrastructure")
include("dokument:presentation")
include("domain")
include("grunnbeløp")
include("hendelse:domain")
include("hendelse:infrastructure")
include("kontrollsamtale:application")
include("kontrollsamtale:domain")
include("kontrollsamtale:infrastructure")
include("oppgave:application")
include("oppgave:domain")
include("oppgave:infrastructure")
include("person:application")
include("person:domain")
include("person:infrastructure")
include("satser")
include("service")
include("statistikk")
include("test-common")
include("tilbakekreving:application")
include("tilbakekreving:domain")
include("tilbakekreving:infrastructure")
include("tilbakekreving:presentation")
include("vedtak:application")
include("vedtak:domain")
include("vilkår:domain")
include("vilkår:fastopphold:domain")
include("vilkår:formue:domain")
include("vilkår:institusjonsopphold:application")
include("vilkår:institusjonsopphold:domain")
include("vilkår:institusjonsopphold:infrastructure")
include("vilkår:institusjonsopphold:presentation")
include("vilkår:uføre:domain")
include("vilkår:utenlandsopphold:application")
include("vilkår:utenlandsopphold:domain")
include("vilkår:utenlandsopphold:infrastructure")
include("web")
include("web-regresjonstest")
include("økonomi:application")
include("økonomi:domain")
include("økonomi:infrastructure")
include("økonomi:presentation")
include("vilkår:flyktning")
findProject(":vilkår:flyktning")?.name = "flyktning"
include("vilkår:flyktning:domain")
findProject(":vilkår:flyktning:domain")?.name = "domain"
