ALTER TABLE sak_statistikk ADD COLUMN id_sekvens BIGINT GENERATED BY DEFAULT AS IDENTITY;
CREATE SEQUENCE sak_statistikk_sekvens;
UPDATE sak_statistikk SET id_sekvens = nextval('sak_statistikk_sekvens') WHERE id_sekvens IS NULL;
ALTER TABLE sak_statistikk ALTER COLUMN id_sekvens SET NOT NULL;
