apiVersion: nais.io/v1
kind: Naisjob
metadata:
  labels:
    team: supstonad
  name: su-datapakke-fritekstavslag
  namespace: supstonad
spec:
  schedule: '*/5 * * * *'
  image: {{ image }}
  concurrencyPolicy: Replace
  vault:
    enabled: true
    paths:
      - mountPath: /var/run/secrets/nais.io/vault
        kvPath: /secret/supstonad/{{ secret_env }}
  webproxy: true
  env:
     {{#each env}}
      - name: {{@key}}
        value: "{{this}}"
     {{/each}}