package no.nav.su.se.bakover.database.statistikk

import no.nav.su.se.bakover.common.person.Fnr
import no.nav.su.se.bakover.common.tid.Tidspunkt
import no.nav.su.se.bakover.test.generer
import statistikk.domain.StønadsklassifiseringDto
import statistikk.domain.StønadstatistikkDto
import statistikk.domain.StønadstatistikkMåned
import java.time.YearMonth
import java.util.UUID

internal fun lagStønadstatistikkRad(
    id: UUID = UUID.randomUUID(),
    måned: YearMonth = YearMonth.of(2026, 5),
    funksjonellTid: Tidspunkt = Tidspunkt.parse("2026-05-15T10:00:00Z"),
    tekniskTid: Tidspunkt = Tidspunkt.parse("2026-05-15T10:01:00Z"),
    sakId: UUID = UUID.randomUUID(),
    stonadstype: StønadstatistikkDto.Stønadstype = StønadstatistikkDto.Stønadstype.SU_ALDER,
    stonadsklassifisering: StønadsklassifiseringDto? = StønadsklassifiseringDto.BOR_ALENE,
) = StønadstatistikkMåned(
    id = id,
    måned = måned,
    funksjonellTid = funksjonellTid,
    tekniskTid = tekniskTid,
    sakId = sakId,
    stonadstype = stonadstype,
    personnummer = Fnr.generer(),
    personNummerEps = Fnr.generer(),
    vedtaksdato = måned.atDay(5),
    vedtakstype = StønadstatistikkDto.Vedtakstype.REVURDERING,
    vedtaksresultat = StønadstatistikkDto.Vedtaksresultat.INNVILGET,
    vedtakFraOgMed = måned.atDay(1),
    vedtakTilOgMed = måned.atEndOfMonth(),
    opphorsgrunn = "opphørsgrunn",
    opphorsdato = måned.atDay(20),
    årsakStans = "årsak stans",
    behandlendeEnhetKode = "4815",
    stonadsklassifisering = stonadsklassifisering,
    sats = 1L,
    utbetales = 2L,
    fradragSum = 3L,
    uføregrad = 4,
    fribeløpEps = 5L,
    alderspensjon = 6,
    alderspensjonEps = 7,
    arbeidsavklaringspenger = 8,
    arbeidsavklaringspengerEps = 9,
    arbeidsinntekt = 10,
    arbeidsinntektEps = 11,
    omstillingsstønad = 12,
    omstillingsstønadEps = 13,
    avtalefestetPensjon = 14,
    avtalefestetPensjonEps = 15,
    avtalefestetPensjonPrivat = 16,
    avtalefestetPensjonPrivatEps = 17,
    bidragEtterEkteskapsloven = 18,
    bidragEtterEkteskapslovenEps = 19,
    dagpenger = 20,
    dagpengerEps = 21,
    fosterhjemsgodtgjørelse = 22,
    fosterhjemsgodtgjørelseEps = 23,
    gjenlevendepensjon = 24,
    gjenlevendepensjonEps = 25,
    introduksjonsstønad = 26,
    introduksjonsstønadEps = 27,
    kapitalinntekt = 28,
    kapitalinntektEps = 29,
    kontantstøtte = 30,
    kontantstøtteEps = 31,
    kvalifiseringsstønad = 32,
    kvalifiseringsstønadEps = 33,
    navYtelserTilLivsopphold = 34,
    navYtelserTilLivsoppholdEps = 35,
    offentligPensjon = 36,
    offentligPensjonEps = 37,
    privatPensjon = 38,
    privatPensjonEps = 39,
    sosialstønad = 40,
    sosialstønadEps = 41,
    statensLånekasse = 42,
    statensLånekasseEps = 43,
    supplerendeStønad = 44,
    supplerendeStønadEps = 45,
    sykepenger = 46,
    sykepengerEps = 47,
    tiltakspenger = 48,
    tiltakspengerEps = 49,
    ventestønad = 50,
    ventestønadEps = 51,
    uføretrygd = 52,
    uføretrygdEps = 53,
    forventetInntekt = 54,
    forventetInntektEps = 55,
    avkortingUtenlandsopphold = 56,
    avkortingUtenlandsoppholdEps = 57,
    underMinstenivå = 58,
    underMinstenivåEps = 59,
    annet = 60,
    annetEps = 61,
    omsorgsstønad = 62,
    omsorgsstønadEps = 63,
)
