dependencies {
    implementation(project(":behandling:domain"))
    implementation(project(":beregning"))
    implementation(project(":common:domain"))
    implementation(project(":dokument:domain"))
    implementation(project(":grunnbeløp"))
    implementation(project(":hendelse:domain"))
    implementation(project(":oppgave:domain"))
    implementation(project(":person:domain"))
    implementation(project(":satser"))
    implementation(project(":tilbakekreving:domain"))
    implementation(project(":vedtak:domain"))
    implementation(project(":vilkår:domain"))
    implementation(project(":vilkår:fastopphold:domain"))
    implementation(project(":vilkår:formue:domain"))
    implementation(project(":vilkår:institusjonsopphold:domain"))
    implementation(project(":vilkår:uføre:domain"))
    implementation(project(":vilkår:flyktning:domain"))
    implementation(project(":vilkår:utenlandsopphold:domain"))
    implementation(project(":økonomi:domain"))

    testImplementation(project(":test-common"))
}
