apiVersion: nais.io/v1
kind: Naisjob
metadata:
  labels:
    team: supstonad
  name: datapakker-soknad
  namespace: supstonad
spec:
  schedule: '1 1 * * *'
  image: {{ image }}
  concurrencyPolicy: Replace