name: tests and build with gradle
description: see above

inputs:
  token:
    description: the github token
    required: true

runs:
  using: "composite"
  steps:
    - name: test and build
      run: ./gradlew test build
      env:
        ORG_GRADLE_PROJECT_githubUser: x-access-token
        ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}