// Contains shared test-data, functions and extension funcions to be used across modules
dependencies {
    api(project(":behandling:behandlinger:domain"))
    api(project(":behandling:common:domain"))
    api(project(":behandling:klage:domain"))
    api(project(":behandling:regulering:domain"))
    api(project(":behandling:revurdering:domain"))
    api(project(":behandling:søknadsbehandling:domain"))
    api(project(":beregning"))
    api(project(":client"))
    api(project(":common:domain"))
    api(project(":common:infrastructure"))
    api(project(":database"))
    api(project(":dokument:domain"))
    api(project(":dokument:infrastructure"))
    api(project(":domain"))
    api(project(":grunnbeløp"))
    api(project(":hendelse:domain"))
    api(project(":hendelse:infrastructure"))
    api(project(":kontrollsamtale:application"))
    api(project(":kontrollsamtale:domain"))
    api(project(":kontrollsamtale:infrastructure"))
    api(project(":nøkkeltall:application"))
    api(project(":nøkkeltall:domain"))
    api(project(":nøkkeltall:infrastructure"))
    api(project(":nøkkeltall:presentation"))
    api(project(":oppgave:domain"))
    api(project(":person:domain"))
    api(project(":satser"))
    api(project(":service"))
    api(project(":tilbakekreving:application"))
    api(project(":tilbakekreving:domain"))
    api(project(":tilbakekreving:infrastructure"))
    api(project(":tilbakekreving:presentation"))
    api(project(":tilgangstyring:application"))
    api(project(":tilgangstyring:domain"))
    api(project(":vedtak:application"))
    api(project(":vedtak:domain"))
    api(project(":vedtak:domain"))
    api(project(":vilkår:bosituasjon:domain"))
    api(project(":vilkår:common"))
    api(project(":vilkår:familiegjenforening:domain"))
    api(project(":vilkår:fastopphold:domain"))
    api(project(":vilkår:flyktning:domain"))
    api(project(":vilkår:formue:domain"))
    api(project(":vilkår:inntekt:domain"))
    api(project(":vilkår:institusjonsopphold:domain"))
    api(project(":vilkår:institusjonsopphold:presentation"))
    api(project(":vilkår:lovligopphold:domain"))
    api(project(":vilkår:opplysningsplikt:domain"))
    api(project(":vilkår:pensjon:domain"))
    api(project(":vilkår:personligoppmøte:domain"))
    api(project(":vilkår:skatt:application"))
    api(project(":vilkår:skatt:domain"))
    api(project(":vilkår:uføre:domain"))
    api(project(":vilkår:utenlandsopphold:domain"))
    api(project(":vilkår:vurderinger:domain"))
    api(project(":vilkår:vurderinger:presentation"))
    api(project(":web"))
    api(project(":økonomi:application"))
    api(project(":økonomi:domain"))
    api(project(":økonomi:infrastructure"))

    compileOnly(rootProject.libs.kotest.assertions.core)
    compileOnly(rootProject.libs.mockito.kotlin)
    compileOnly(rootProject.libs.mockito)
    compileOnly(rootProject.libs.jsonassert)
    compileOnly(rootProject.libs.embedded.postgres) {
        exclude("org.apache.commons", "commons-compress")
    }
    api(rootProject.libs.wiremock) {
        exclude(group = "junit")
    }
}
