#    permissions:
#      contents: 'write' # needed to create/edit releases
#      pull-requests: 'write' # needed to add labels to pull requests

name: 'Draft release'
description: 'Appends all PR descriptions to a draft release (creates/edits). Also adds labels to PRs'

inputs:
  github-token:
    description: 'The GitHub token to use for authentication'
    required: true
runs:
  using: "composite"
  steps:
    - uses: release-drafter/release-drafter@v6
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
