name: 'Build and test'
description: 'Checkout, download java and assemble and test'

inputs:
  gradle-arguments:
    required: false
    description: 'Gradle arguments to pass to gradle build'
    default: build
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/setup-java
    - name: Run gradle build
      uses: gradle/gradle-build-action@v2.11.1
      with:
        gradle-version: wrapper
        arguments: ${{ inputs.gradle-arguments }}
