name: 'Push image'
description: 'Push image'

inputs:
  identity_provider:
    required: true
    description: 'secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER'
  project_id:
    required: true
    description: 'vars.NAIS_MANAGEMENT_PROJECT_ID'
  tag:
    required: true
    description: 'github.sha'
  dockerfile:
    required: false
    description: 'Optional dockerfile path, default: Dockerfile'
    default: 'Dockerfile'
  image_suffix:
    required: false
    description: 'Optional, default empty'
    default: ''
outputs:
  image:
    description: "Docker image in GAR"
    value: ${{ steps.docker-build-push.outputs.image }}

runs:
  using: "composite"
  steps:
    - uses: nais/docker-build-push@v0
      id: docker-build-push
      with:
        team: supstonad
        tag: ${{ inputs.tag }}
        identity_provider: ${{ inputs.identity_provider }}
        project_id: ${{ inputs.project_id }}
        dockerfile: ${{ inputs.dockerfile }}
        image_suffix: ${{ inputs.image_suffix }}
