apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: su-se-statistikk
  namespace: supstonad
  labels:
    team: supstonad
spec:
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: elastic
        - id: loki
  image: "{{image}}"
  port: 8080
  ingresses:
    - https://su-se-statistikk.intern.dev.nav.no
  liveness:
    initialDelay: 20
    path: /health/isalive
  readiness:
    initialDelay: 5
    path: /health/isready
  replicas:
    max: 1
    min: 1
  resources:
    requests:
      cpu: 10m
  prometheus:
    enabled: true
    path: /metrics
#  azure:
    sidecar:
      enabled: true
      autoLogin: true
  kafka:
    pool: nav-dev
  env:
  accessPolicy:
    outbound:
      rules:
    inbound:
      rules: