package tilbakekreving.presentation.api

import io.ktor.server.routing.Route
import tilbakekreving.application.service.forhåndsvarsel.ForhåndsvarsleTilbakekrevingsbehandlingService
import tilbakekreving.application.service.opprett.OpprettTilbakekrevingsbehandlingService
import tilbakekreving.application.service.vurder.BrevTilbakekrevingsbehandlingService
import tilbakekreving.application.service.vurder.MånedsvurderingerTilbakekrevingsbehandlingService
import tilbakekreving.presentation.api.forhåndsvarsel.forhåndsvarsleTilbakekrevingRoute
import tilbakekreving.presentation.api.opprett.opprettTilbakekrevingsbehandlingRoute
import tilbakekreving.presentation.api.vurder.brevTilbakekrevingsbehandlingRoute
import tilbakekreving.presentation.api.vurder.månedsvurderingerTilbakekrevingsbehandlingRoute

internal const val TILBAKEKREVING_PATH = "saker/{sakId}/tilbakekreving"

fun Route.tilbakekrevingRoutes(
    opprettTilbakekrevingsbehandlingService: OpprettTilbakekrevingsbehandlingService,
    månedsvurderingerTilbakekrevingsbehandlingService: MånedsvurderingerTilbakekrevingsbehandlingService,
    brevTilbakekrevingsbehandlingService: BrevTilbakekrevingsbehandlingService,
    forhåndsvarsleTilbakekrevingsbehandlingService: ForhåndsvarsleTilbakekrevingsbehandlingService,
) {
    this.opprettTilbakekrevingsbehandlingRoute(opprettTilbakekrevingsbehandlingService)
    this.månedsvurderingerTilbakekrevingsbehandlingRoute(månedsvurderingerTilbakekrevingsbehandlingService)
    this.brevTilbakekrevingsbehandlingRoute(brevTilbakekrevingsbehandlingService)
    this.forhåndsvarsleTilbakekrevingRoute(forhåndsvarsleTilbakekrevingsbehandlingService)
}
