apiVersion: nais.io/v1
kind: Naisjob
metadata:
  labels:
    team: supstonad
  name: su-datapakke-fritekst
  namespace: supstonad
spec:
  # Run every day at 3:15
  schedule: '15 3 * * *'
  image: {{ image }}
  concurrencyPolicy: Replace
  vault:
    enabled: true
    paths:
      - mountPath: /var/run/secrets/nais.io/vault
        kvPath: /secret/supstonad/prod
  webproxy: true
  env:
    - name: GCP_PROJECT
      value: "supstonad-prod-9599"
    - name: VAULT_MOUNTPATH
      value: "postgresql/prod-fss/"
    - name: DATABASE_NAME
      value: "supstonad-db-15-prod"
    - name: DATABASE_JDBC_URL
      value: "jdbc:postgresql://A01DBVL036.adeo.no:5432/supstonad-db-15-prod"