# requires permission contents: 'write'

name: 'Submit dependecy graph'
description: 'Submit dependecy graph'
runs:
  using: "composite"

  steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/setup-java
    - name: Submit dependency graph
      uses: gradle/setup-gradle@v3
      with:
        gradle-version: wrapper
        dependency-graph: generate-and-submit
        arguments: assemble testClasses
