# requires permission contents: 'write'

name: 'Submit dependecy graph'
description: 'Submit dependecy graph'
runs:
  using: "composite"

  steps:
    - uses: actions/checkout@v5
    - uses: ./.github/actions/setup-java
    - name: Submit dependency graph
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: wrapper
        dependency-graph: generate-and-submit
    - shell: bash
      run: ./gradlew assemble testClasses
