name: Submit dependency graph

on:
  workflow_call:

permissions: {}

jobs:
  submit-dependency-graph:
    runs-on: ubuntu-latest
    name: Submit dependency graph
    permissions:
      contents: 'write'
    steps:
      - uses: actions/checkout@v5
      - name: Submit dependency graph
        uses: ./.github/actions/submit-dependency-graph
