name: Deploy

on:
  workflow_call:
    inputs:
      cluster:
        required: true
        description: 'dev-fss/prod-fss'
        type: string
      var:
        required: false
        description: 'Optional, default empty, format: key1=value1,key2=value2'
        type: string
        default: ''
      resource:
        required: false
        description: 'Optional, default nais.yml, path to nais.yml'
        default: 'nais.yml'
        type: string
      vars:
        required: false
        description: 'Optional, default empty, path to nais-dev.json/nais-prod.json'
        default: ''
        type: string

permissions: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to ${{ inputs.cluster }}
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to ${{ inputs.cluster }}
        uses: ./.github/actions/deploy
        with:
          cluster: ${{ inputs.cluster }}
          var: ${{ inputs.var }}
          vars: ${{ inputs.vars }}
          resource: ${{ inputs.resource }}
