name: Build branch/PR
# If you want to deploy your branch see branch-deploy.yml
on:
  push:
    branches:
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch
      - '!master'   # excludes master
      - '!main'     # excludes main (will probably replace master)
    paths-ignore:
      - '.github/**'
      - '!.github/workflows/su-se-bakover-branch.yml'
      - '!.github/actions/build-and-test/**'
      - '!.github/actions/setup-java/**'
      - '.idea/**'
      - 'datapakker/**'
      - 'local-db-scripts/**'
      - 'scripts/**'
      - '.editorconfig'
      - '*.template'
      - '.gitignore'
      - 'alerts.yml'
      - '*.sh'
      - 'CODEOWNERS'
      - 'docker-compose.yml'
      - 'LICENSE'
      - '*.md'

permissions: {}

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest-8-cores
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5
      - name: Build and test
        uses: ./.github/actions/build-and-test
