name: Deploy to prod automatically on published release

on:
  release:
    types: [published]

permissions: {}

jobs:
  deploy_to_prod:
    name: Deploy to prod
    permissions:
      contents: read
      id-token: write
    uses: navikt/su-se-bakover/.github/workflows/reusable-deploy.yml@master
    with:
      var: image=europe-north1-docker.pkg.dev/nais-management-233d/supstonad/su-se-bakover-app:${{ github.sha }}
      cluster: prod-fss
      vars: nais-prod.json
      resource: .nais/prod.yaml
