#!/bin/sh

echo '[git pre-commit hook] executing gradle spotlessApply before commit.'

stagedFiles=$(git diff --name-only --cached)
if [ -z "${stagedFiles-unset}" ]; then
  echo "No staged files, aborting..."
  exit 0
fi

committedFiles=$(git diff --name-only --cached --diff-filter=d)
files=$(echo $committedFiles | tr ";" "\\n")

# Run checks
./gradlew spotlessApply --daemon
status=$?

echo "finished spotlessApply, status: $status"

if [ "$status" -gt 0 ];
then
  echo "Error running spotlessApply, aborting..."
else
    for file in $files
    do
        git add $file
    done
fi

# Exit with status from test-run: nonzero prevents commit
exit $status
